FROM python:3.9


WORKDIR /code
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY ./requirements.dev.txt /code/requirements.dev.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.dev.txt
